---
# starting from the "simple" preset gives us:
# - the Conventional Commits convention
preset: "simple"
changelog:
  path: "CHANGELOG.md"
  sections:
    "Added": "^feat$"
    "Fixed": "^fix$"
releaseTypes:
  enabled:
    - mainline
    - maturity
    - internal
  publicationServices:
    - github
  items:
    mainline:
      description: "{{#fileContent}}CHANGELOG.md{{/fileContent}}"
      filterTags: "^({{configuration.releasePrefix}})?([0-9]\\d*)\\.([0-9]\\d*)\\.([0-9]\\d*)$"
      gitPush: "true"
      gitTag: "true"
      matchBranches: "^(master|main)$"
      matchEnvironmentVariables:
        CI: "^true$"                 # only match this release type when running on CI servers
      matchWorkspaceStatus: "CLEAN"  # only match this release type when the repository is clean
      publish: "true"
    maturity:
      description: "{{#fileContent}}CHANGELOG.md{{/fileContent}}"
      collapseVersions: true
      collapsedVersionQualifier: "{{#sanitizeLower}}{{branch}}{{/sanitizeLower}}"
      filterTags: "^({{configuration.releasePrefix}})?([0-9]\\d*)\\.([0-9]\\d*)\\.([0-9]\\d*)(-(alpha|beta)(\\.([0-9]\\d*))?)?$"
      gitPush: "true"
      gitTag: "true"
      matchBranches: "^(alpha|beta)$"
      matchWorkspaceStatus: "CLEAN"  # only match this release type when the repository is clean
      publish: "true"
      publishPreRelease: "true"
    # "internal" overrides the release type with the same name from the preset adding some qualifiers and is the global fallback for all release types
    internal:
      collapseVersions: true
      collapsedVersionQualifier: "internal"
      gitPush: "false"
      gitTag: "false"
      identifiers:
        -
          qualifier: "{{#sanitizeLower}}{{branch}}{{/sanitizeLower}}"
          position: "BUILD"
        -
          qualifier: "{{#short5}}{{releaseScope.finalCommit}}{{/short5}}"
          position: "BUILD"
        -
          qualifier: "{{#timestampYYYYMMDDHHMMSS}}{{timestamp}}{{/timestampYYYYMMDDHHMMSS}}"
          position: "BUILD"
      publish: "false"
      publishPreRelease: "false"
services:
  github:
    type: "GITHUB"
    options:
      AUTHENTICATION_TOKEN: "{{#environmentVariable}}GH_TOKEN{{/environmentVariable}}"
      REPOSITORY_NAME: "expression-parser"
      REPOSITORY_OWNER: "vgarciabnz"